# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fileattribute.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_attribute_dialog(object):
    def setupUi(self, attribute_dialog):
        attribute_dialog.setObjectName("attribute_dialog")
        attribute_dialog.resize(380, 357)
        attribute_dialog.setMinimumSize(QtCore.QSize(380, 357))
        attribute_dialog.setMaximumSize(QtCore.QSize(380, 357))
        self.verticalLayout = QtWidgets.QVBoxLayout(attribute_dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.name_widget = QtWidgets.QWidget(attribute_dialog)
        self.name_widget.setObjectName("name_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.name_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name_label = QtWidgets.QLabel(self.name_widget)
        self.name_label.setObjectName("name_label")
        self.horizontalLayout.addWidget(self.name_label)
        self.name_lineEdit = QtWidgets.QLineEdit(self.name_widget)
        self.name_lineEdit.setReadOnly(True)
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.horizontalLayout.addWidget(self.name_lineEdit)
        self.verticalLayout.addWidget(self.name_widget)
        self.type_widget = QtWidgets.QWidget(attribute_dialog)
        self.type_widget.setObjectName("type_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.type_widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.type_label = QtWidgets.QLabel(self.type_widget)
        self.type_label.setObjectName("type_label")
        self.horizontalLayout_2.addWidget(self.type_label)
        self.type_lineEdit = QtWidgets.QLineEdit(self.type_widget)
        self.type_lineEdit.setReadOnly(True)
        self.type_lineEdit.setObjectName("type_lineEdit")
        self.horizontalLayout_2.addWidget(self.type_lineEdit)
        self.verticalLayout.addWidget(self.type_widget)
        self.size_widget = QtWidgets.QWidget(attribute_dialog)
        self.size_widget.setObjectName("size_widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.size_widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.size_label = QtWidgets.QLabel(self.size_widget)
        self.size_label.setObjectName("size_label")
        self.horizontalLayout_3.addWidget(self.size_label)
        self.sieze_lineEdit = QtWidgets.QLineEdit(self.size_widget)
        self.sieze_lineEdit.setReadOnly(True)
        self.sieze_lineEdit.setObjectName("sieze_lineEdit")
        self.horizontalLayout_3.addWidget(self.sieze_lineEdit)
        self.verticalLayout.addWidget(self.size_widget)
        self.create_widget = QtWidgets.QWidget(attribute_dialog)
        self.create_widget.setObjectName("create_widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.create_widget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ctime_label = QtWidgets.QLabel(self.create_widget)
        self.ctime_label.setObjectName("ctime_label")
        self.horizontalLayout_4.addWidget(self.ctime_label)
        self.ctime_lineEdit = QtWidgets.QLineEdit(self.create_widget)
        self.ctime_lineEdit.setReadOnly(True)
        self.ctime_lineEdit.setObjectName("ctime_lineEdit")
        self.horizontalLayout_4.addWidget(self.ctime_lineEdit)
        self.verticalLayout.addWidget(self.create_widget)
        self.modify_widget = QtWidgets.QWidget(attribute_dialog)
        self.modify_widget.setObjectName("modify_widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.modify_widget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.mtime_label = QtWidgets.QLabel(self.modify_widget)
        self.mtime_label.setObjectName("mtime_label")
        self.horizontalLayout_5.addWidget(self.mtime_label)
        self.mtime_lineEdit = QtWidgets.QLineEdit(self.modify_widget)
        self.mtime_lineEdit.setReadOnly(True)
        self.mtime_lineEdit.setObjectName("mtime_lineEdit")
        self.horizontalLayout_5.addWidget(self.mtime_lineEdit)
        self.verticalLayout.addWidget(self.modify_widget)

        self.retranslateUi(attribute_dialog)
        QtCore.QMetaObject.connectSlotsByName(attribute_dialog)

    def retranslateUi(self, attribute_dialog):
        _translate = QtCore.QCoreApplication.translate
        attribute_dialog.setWindowTitle(_translate("attribute_dialog", "文件属性"))
        self.name_label.setText(_translate("attribute_dialog", "文件名称"))
        self.type_label.setText(_translate("attribute_dialog", "文件类型"))
        self.size_label.setText(_translate("attribute_dialog", "文件大小"))
        self.ctime_label.setText(_translate("attribute_dialog", "创建时间"))
        self.mtime_label.setText(_translate("attribute_dialog", "修改时间"))
