# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fileSystem.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_filesystem(object):
    def setupUi(self, filesystem):
        filesystem.setObjectName("filesystem")
        filesystem.resize(1081, 871)
        self.verticalLayout = QtWidgets.QVBoxLayout(filesystem)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.path_widget = QtWidgets.QWidget(filesystem)
        self.path_widget.setMinimumSize(QtCore.QSize(0, 25))
        self.path_widget.setMaximumSize(QtCore.QSize(16777215, 25))
        self.path_widget.setObjectName("path_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.path_widget)
        self.horizontalLayout.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.path_btn = QtWidgets.QPushButton(self.path_widget)
        self.path_btn.setMinimumSize(QtCore.QSize(45, 25))
        self.path_btn.setMaximumSize(QtCore.QSize(45, 25))
        self.path_btn.setText("")
        self.path_btn.setCheckable(True)
        self.path_btn.setObjectName("path_btn")
        self.horizontalLayout.addWidget(self.path_btn)
        self.path_lineedit = QtWidgets.QLineEdit(self.path_widget)
        self.path_lineedit.setMinimumSize(QtCore.QSize(2, 25))
        self.path_lineedit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.path_lineedit.setObjectName("path_lineedit")
        self.horizontalLayout.addWidget(self.path_lineedit)
        self.jmp_btn = QtWidgets.QPushButton(self.path_widget)
        self.jmp_btn.setMinimumSize(QtCore.QSize(45, 25))
        self.jmp_btn.setMaximumSize(QtCore.QSize(45, 25))
        self.jmp_btn.setText("")
        self.jmp_btn.setObjectName("jmp_btn")
        self.horizontalLayout.addWidget(self.jmp_btn)
        self.verticalLayout.addWidget(self.path_widget)
        self.listWidget = QtWidgets.QListWidget(filesystem)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)

        self.retranslateUi(filesystem)
        QtCore.QMetaObject.connectSlotsByName(filesystem)

    def retranslateUi(self, filesystem):
        _translate = QtCore.QCoreApplication.translate
        filesystem.setWindowTitle(_translate("filesystem", "文件资源管理"))
