# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_viwindow(object):
    def setupUi(self, viwindow):
        viwindow.setObjectName("viwindow")
        viwindow.resize(595, 517)
        self.verticalLayout = QtWidgets.QVBoxLayout(viwindow)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.input = QtWidgets.QTextEdit(viwindow)
        self.input.setStyleSheet("background-color: rgb(79, 79, 79);\n"
"color: rgb(255, 255, 255);")
        self.input.setObjectName("input")
        self.verticalLayout.addWidget(self.input)

        self.retranslateUi(viwindow)
        QtCore.QMetaObject.connectSlotsByName(viwindow)

    def retranslateUi(self, viwindow):
        _translate = QtCore.QCoreApplication.translate
        viwindow.setWindowTitle(_translate("viwindow", "Vi"))
